name: Atualização dos dados
on: 
  push

env:
  LANG: "pt_BR.UTF-8"
  
jobs: 
  atualizacao-dados: 
    if: github.actor == 'davisrodrigues' && github.event.commits[0].message == 'Atualização'
    
    runs-on: ubuntu-latest
    
    steps:                
      - name: Obter dados do evento que disparou o workflow
        run: |
             echo "event_name: ${event_name}"
             echo "git_ref: ${git_ref}"
        env: 
             event_name: ${{ github.event_name }}
             git_ref: ${{ github.event.ref }}

      - name: Copiar repositório para a máquina virtual
        uses: actions/checkout@v2

      - name: Configurar Python 3.7.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.6
                
      - name: Versão do Python em uso
        run: python -c "import sys; print(sys.version)"

      - name: Instalar dependências
        run: |
             python -m pip install --upgrade pip
             pip install pandas plotly nbimporter numpy papermill ipykernel jupyter
      
      - name: Mudar locale para pt_BR.UTF-8
        run: |
          sudo locale-gen pt_BR.UTF-8
          sudo update-locale LANG=pt_BR.UTF-8
          
      - name: Teste do locale
        run: |
          date
      
      - name: Executar notebooks
        id: update_nb
        run: |
             sh executar-notebooks.sh

      - name: Fazer o commit das alterações
        run: |
             git config --global user.email "github-actions[bot]@users.noreply.github.com"
             git config --global user.name "github-actions[bot]"
             git add -- ./docs/graficos ./docs/serviceWorker.js
             git commit -m '[bot] Atualização diária dos dados' -- ./docs/graficos ./docs/serviceWorker.js
             git push