name: Atualização dos dados
on: 
  push

env:
  LANG: "pt_BR.UTF-8"
  
jobs: 
  atualizacao-dados: 
    if: github.actor == 'davisrodrigues'
    
    runs-on: ubuntu-latest
    
    steps:                
      - name: Desfazer todos os commits de hoje
        run: |
             git rebase -i 3597ad5400ddcf86e7ebd5a9345efc37907060d1