name: Atualização dos dados
on:
  push:
  schedule:
    - cron: '30 21,1 * * *'

env:
  LANG: "pt_BR.UTF-8"
  
jobs: 
  atualizacao-dados: 
    if: github.actor == 'davisrodrigues'
    
    runs-on: ubuntu-latest
    
    steps:                
      - name: Obter dados do evento que disparou o workflow
        run: |
             echo "event_name: ${event_name}"
             echo "git_ref: ${git_ref}"
        env: 
             event_name: ${{ github.event_name }}
             git_ref: ${{ github.event.ref }}
        
      - name: Instalar Java 11 - requisito tabula-py
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk
          
      - name: Testar Java 11
        run: java -version

      - name: Configurar Python 3.7.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.7
          
      - name: Testar Python 3.7.7
        run: python -c "import sys; print(sys.version)"

      - name: Instalar dependências Python
        run: |
             python -m pip install --upgrade pip
             pip install pandas plotly requests beautifulsoup4 tabula-py
      
      - name: Mudar locale para pt_BR.UTF-8 e horário para BRT
        run: |
          sudo locale-gen pt_BR.UTF-8
          sudo update-locale LANG=pt_BR.UTF-8
          echo "America/Sao_Paulo" | sudo tee /etc/timezone
          sudo dpkg-reconfigure --frontend noninteractive tzdata
          date
      
      - name: Copiar repositório para a máquina virtual
        uses: actions/checkout@v2
        
      - name: Atualizar o repositório (para os casos de re-execução)
        run: git pull

      - name: Gerar gráficos e tabelas com os dados municipais e estaduais
        run: python covid19sp.py

      - name: Fazer o commit das alterações
        run: |
             git config --global user.email "github-actions[bot]@users.noreply.github.com"
             git config --global user.name "github-actions[bot]"
             git add -- ./dados ./docs/graficos ./docs/serviceWorker.js
             git commit -m "[bot] Atualização dos dados | `date +'%d/%m/%y %H:%M:%S'`" -- ./dados ./docs/graficos ./docs/serviceWorker.js
             git push